/*
-- Query: SELECT * FROM demo_prestashop.reparto
LIMIT 0, 1000

-- Date: 2020-06-05 16:12
*/
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Tom Hanks');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Robin Wright Penn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Gary Sinise');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Mykelti Williamson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Sally Field');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Rebecca Williams');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Michael Conner Humphreys');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Harold G. Herthum');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Haley Joel Osment');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'George Kelly');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Bob Penny');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'John Randall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Sam Anderson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Margo Moorer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Ione M. Telech');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (1,'Christine Seabrook');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Leonardo DiCaprio');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Kate Winslet');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Billy Zane');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Kathy Bates');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Frances Fisher');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Bernard Hill');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Jonathan Hyde');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Danny Nucci');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'David Warner');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Bill Paxton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Gloria Stuart');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Victor Garber');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (2,'Suzy Amis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Marlon Brando');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Al Pacino');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'James Caan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Robert Duvall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Diane Keaton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'John Cazale');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Talia Shire');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Richard Castellano');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Sterling Hayden');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Gianni Russo');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Rudy Bond');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'John Marley');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Richard Conte');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Al Lettieri');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Abe Vigoda');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (3,'Franco Citti');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Russell Crowe');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Joaquin Phoenix');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Connie Nielsen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Oliver Reed');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Richard Harris');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Derek Jacobi');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Djimon Hounsou');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'David Schofield');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'John Shrapnel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Tomas Arana');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Ralf Moeller');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Spencer Treat Clark');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'David Hemmings');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Tommy Flanagan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Sven-Ole Thorsen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (4,'Tony Curran');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Elijah Wood');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Viggo Mortensen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Ian McKellen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Sean Astin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Andy Serkis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'John Rhys-Davies');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Orlando Bloom');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'John Noble');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Miranda Otto');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'David Wenham');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Bernard Hill');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Billy Boyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Dominic Monaghan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Liv Tyler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Karl Urban');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Ian Holm');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Hugo Weaving');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Cate Blanchett');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (5,'Lawrence Makoare');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Christian Bale');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Heath Ledger');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Aaron Eckhart');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Michael Caine');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Gary Oldman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Maggie Gyllenhaal');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Morgan Freeman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Eric Roberts');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Cillian Murphy');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Anthony Michael Hall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Michael Jai White');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'William Fichtner');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Edison Chen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Monique Curnen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Chin Han');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Nestor Carbonell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Ritchie Coster');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Keith Szarabajka');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Colin McFarlane');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Melinda McGraw');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Nathan Gamble');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (6,'Michael Vieau');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (7 ,'Tim Robbins');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (7,'Morgan Freeman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (7,'Bob Gunton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (7,'James Whitmore');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (7,'Gil Bellows');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (7,'William Sadler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (7,'Mark Rolston');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (7,'Clancy Brown');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (8,'Johnny Depp');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (8,'Geoffrey Rush');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (8,'Orlando Bloom');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (8,'Keira Knightley');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (8,'Jonathan Pryce');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (8,'Jack Davenport');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (8,'Mackenzie Crook');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (8,'Zoe Saldana');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (8,'Kevin R. McNally');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,' Mel Gibson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,'Sophie Marceau');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,'Patrick McGoohan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,'Catherine McCormack');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,'James Cosmo');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,'Brendan Gleeson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,'Brian Cox');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,'Peter Mullan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,'Gerard McSorley');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (9,'Angus MacFadyen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (10 ,'Liam Neeson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (10,'Ben Kingsley');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (10,'Ralph Fiennes');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (10,'Caroline Goodall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (10,'Jonathan Sagall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (10,'Embeth Davidtz');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (11 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (12 ,'Johnny Depp');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (12,'Winona Ryder');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (12,'Dianne Wiest');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (12,'Anthony Michael Hall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (12,'Alan Arkin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (12,'Kathy Baker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (12,'Vincent Price');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (12,'Caroline Aaron');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (12,'Robert Oliveri');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13 ,'Elijah Wood');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Ian McKellen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Viggo Mortensen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Sean Astin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Sean Bean');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Cate Blanchett');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Hugo Weaving');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Liv Tyler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Ian Holm');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Christopher Lee');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'John Rhys-Davies');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Orlando Bloom');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Dominic Monaghan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Billy Boyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Lawrence Makoare');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Craig Parker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Marton Csokas');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (13,'Andy Serkis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14 ,'Tom Hanks');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Tom Sizemore');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Edward Burns');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Barry Pepper');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Adam Goldberg');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Vin Diesel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Giovanni Ribisi');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Jeremy Davies');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Matt Damon');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Ted Danson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Paul Giamatti');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Dennis Farina');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Joerg Stadler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Max Martini');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Dylan Bruno');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (14,'Bryan Cranston');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (15 ,'Michael J. Fox');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (15,'Christopher Lloyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (15,'Lea Thompson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (15,'Crispin Glover');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (15,'Claudia Wells');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (15,'Thomas F. Wilson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (15,'Billy Zane');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (15,'Sachi Parker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (16 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (17 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18 ,'Elijah Wood');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Viggo Mortensen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Ian McKellen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Sean Astin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Andy Serkis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'John Rhys-Davies');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Orlando Bloom');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Bernard Hill');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Miranda Otto');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'David Wenham');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Dominic Monaghan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Billy Boyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Christopher Lee');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Liv Tyler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Karl Urban');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Brad Dourif');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Hugo Weaving');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Cate Blanchett');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (18,'Craig Parker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19 ,'Daniel Radcliffe');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Rupert Grint');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Emma Watson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Michael Gambon');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Gary Oldman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Timothy Spall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Tom Felton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'David Thewlis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Dawn French');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Emma Thompson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Julie Christie');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Robbie Coltrane');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Peter Best');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Julie Walters');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Maggie Smith');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Alan Rickman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Richard Griffiths');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Fiona Shaw');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Bonnie Wright');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Mark Williams');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Chris Rankin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'David Bradley');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Oliver Phelps');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'James Phelps');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Matthew Lewis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Devon Murray');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Jamie Waylett');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Josh Herdman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Alfie Enoch');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Miriam Margolyes');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Gemma Jones');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Harry Melling');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Robert Hardy');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Warwick Davis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Edward Randell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Pam Ferris');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Emily Da le');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Danielle Tabor');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Jimmy Gardner');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Lenny Henry');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Lee Ingleby');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Adrian Rawlins');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (19,'Geraldine Somerville');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20 ,'Edward Norton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Edward Furlong');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Fairuza Balk');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Stacy Keach');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Elliott Gould');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Avery Brooks');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Beverly D\'Angelo');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Jennifer Lien');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Guy Torry');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Ethan Suplee');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (20,'Keram Malicki-Sanchez');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21 ,'Gerard Butler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Lena Headey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'David Wenham');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Dominic West');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Vincent Regan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Rodrigo Santoro');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Michael Fassbender');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Andrew Tieman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Andrew Pleavin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Tom Wisdom');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Tim Conolly');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Tyler Max Neitzel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Mercedes Leggett');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (21,'Peter Mensah');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22 ,'Bruce Willis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22,'Toni Collette');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22,'Haley Joel Osment');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22,'Olivia Williams');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22,'Trevor Morgan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22,'Donnie Wahlberg');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22,'Peter Tambakis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22,'Jeffrey Zubernis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22,'Bruce Norris');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (22,'KaDee Strickland');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23 ,'John Travolta');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Samuel L. Jackson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Uma Thurman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Bruce Willis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Harvey Keitel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Eric Stoltz');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Tim Roth');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Maria de Medeiros');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Amanda Plummer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Ving Rhames');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Rosanna Arquette');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Christopher Walken');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Quentin Tarantino');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Peter Greene');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (23,'Phil LaMarr');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24 ,'Natalie Portman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Hugo Weaving');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Stephen Rea');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'John Hurt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Stephen Fry');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Rupert Graves');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Tim Pigott-Smith');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Roger Allam');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Ben Miles');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Sinead Cusack');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Natasha Wightman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Eddie Marsan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (24,'Billie Cook');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25 ,'Jodie Foster');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Anthony Hopkins');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Scott Glenn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Ted Levine');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Anthony Heald');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Diane Baker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Brooke Smith');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Tracey Walter');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Kasi Lemmons');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Chris Isaak');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Roger Corman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Frankie Faison');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (25,'Paul Lazar');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (26 ,'Sylvester Stallone');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (26,'Talia Shire');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (26,'Burt Young');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (26,'Carl Weathers');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (26,'Burgess Meredith');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (26,'Thayer David');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (26,'Joe Spinell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27 ,'Brad Pitt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27,'Edward Norton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27,'Helena Bonham Carter');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27,'Meat Loaf');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27,'Jared Leto');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27,'Van Quattro');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27,'Markus Redmond');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27,'Michael Girardin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27,'Rachel Singer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (27,'Eion Bailey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (28 ,'Henry Thomas');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (28,'Dee Wallace');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (28,'Robert MacNaughton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (28,'Drew Barrymore');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (28,'Peter Coyote');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (28,'C. Thomas Howell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (28,'K.C. Martel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (28,'Sean Frye');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (28,'Erika Eleniak');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29 ,'Sam Neill');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'Laura Dern');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'Jeff Goldblum');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'Richard Attenborough');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'Ariana Richards');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'Joseph Mazzello');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'Wayne Knight');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'Samuel L. Jackson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'Bob Peck');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'Martin Ferrero');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (29,'B.D. Wong');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (30 ,'Keanu Reeves');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (30,'Laurence Fishburne');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (30,'Carrie-Anne Moss');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (30,'Hugo Weaving');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (30,'Joe Pantoliano');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (30,'Marcus Chong');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (30,'Paul Goddard');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (30,'Gloria Foster');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31 ,'Tom Hanks');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Michael Clarke Duncan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'David Morse');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Michael Jeter');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Doug Hutchison');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Sam Rockwell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Barry Pepper');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Jeffrey DeMunn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Bonnie Hunt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'James Cromwell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Graham Greene');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Gary Sinise');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Harry Dean Stanton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Patricia Clarkson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'William Sadler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (31,'Paula Malcomson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (32 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (33 ,'John Travolta');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (33,'Olivia Newton-John');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (33,'Stockard Channing');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (33,'Jeff Conaway');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (33,'Didi Conn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (33,'Lorenzo Lamas');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (33,'Dinah Manoff');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (33,'Barry Pearl');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (33,'Michael Tucci');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Al Pacino');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Robert De Niro');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Diane Keaton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Robert Duvall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'James Caan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'John Cazale');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Lee Strasberg');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Talia Shire');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Marianna Hill');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Danny Aiello');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Harry Dean Stanton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Troy Donahue');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Roger Corman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (34,'Morgana King');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (35 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36 ,'Robert Downey Jr.');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36,'Terrence Howard');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36,'Gwyneth Paltrow');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36,'Jeff Bridges');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36,'Stan Lee');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36,'Leslie Bibb');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36,'Clark Gregg');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36,'Shaun Toub');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36,'Faran Tahir');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (36,'Samuel L. Jackson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37 ,'Linda Blair');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37,'Max von Sydow');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37,'Ellen Burstyn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37,'Jason Miller');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37,'Lee J. Cobb');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37,'Kitty Winn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37,'Jack MacGowran');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37,'Arthur Storch');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37,'Barton Heyman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (37,'Gina Petrushka');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Johnny Depp');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Orlando Bloom');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Keira Knightley');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Stellan Skarsgård');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Bill Nighy');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Naomie Harris');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Jonathan Pryce');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Jack Davenport');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Lee Arenberg');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Mackenzie Crook');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Kevin McNally');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (38,'Geoffrey Rush');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (39 ,'Brad Pitt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (39,'Morgan Freeman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (39,'Gwyneth Paltrow');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (39,'Kevin Spacey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (39,'John C. McGinley');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (39,'Richard Roundtree');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (39,'R. Lee Ermey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (39,'Leland Orser');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (39,'Richard Schiff');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (40 ,'Arnold Schwarzenegger');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (40,'Linda Hamilton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (40,'Edward Furlong');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (40,'Robert Patrick');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (40,'Earl Boen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (40,'Joe Morton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (40,'Jenette Goldstein');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41 ,'Jack Nicholson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Shelley Duvall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Danny Lloyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Scatman Crothers');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Barry Nelson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Philip Stone');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Joe Turkel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Lia Beldman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Billie Gibson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Barry Denne');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'David Baxt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Manning Redwood');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Kisa Burns');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Louise Burns');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Alison Coleridge');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (41,'Norman Gay');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (42 ,'Tommy Lee Jones');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (42,'Will Smith');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (42,'Linda Fiorentino');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (42,'Vincent D\'Onofrio');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (42,'Sergio Calderón');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (42,'Rip Torn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (42,'Siobhan Fallon');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (42,'Tony Shalhoub');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (42,'Verne Troyer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43 ,'Tobey Maguire');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43,'Kirsten Dunst');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43,'Willem Dafoe');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43,'James Franco');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43,'Rosemary Harris');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43,'Cliff Robertson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43,'J.K. Simmons');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43,'Bruce Campbell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43,'Bill Nunn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (43,'Stan Lee');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (44 ,'Michael J. Fox');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (44,'Christopher Lloyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (44,'Lea Thompson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (44,'Thomas F. Wilson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (44,'Elisabeth Shue');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (44,'Charles Fleischer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (44,'Joe Flaherty');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (44,'Harry Waters Jr.');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (44,'Billy Zane');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (45 ,'Jim Carrey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (45,'Laura Linney');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (45,'Noah Emmerich');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (45,'Natascha McElhone');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (45,'Ed Harris');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (45,'Holland Taylor');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (45,'Paul Giamatti');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (46 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (47 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48 ,'Mark Hamill');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Harrison Ford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Carrie Fisher');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Peter Cushing');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Alec Guinness');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'David Prowse');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Peter Mayhew');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Anthony Daniels');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Kenny Baker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Phil Brown');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Shelagh Fraser');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Alex McCrindle');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (48,'Jack Purvis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49 ,'Cary Elwes');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49,'Leigh Whannell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49,'Danny Glover');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49,'Monica Potter');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49,'Dina Meyer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49,'Tobin Bell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49,'Shawnee Smith');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49,'Ken Leung');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49,'Alexandra Bokyun Chun');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (49,'Michael Emerson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50 ,'Arnold Schwarzenegger');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50,'Linda Hamilton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50,'Michael Biehn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50,'Paul Winfield');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50,'Lance Henriksen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50,'Rick Rossovich');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50,'Bess Motta');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50,'Earl Boen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50,'Dick Miller');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (50,'Bill Paxton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51 ,'Uma Thurman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'Lucy Liu');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'Daryl Hannah');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'Vivica A. Fox');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'Sonny Chiba');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'Chiaki Kuriyama');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'Michael Bowen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'Julie Dreyfus');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'Michael Parks');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'David Carradine');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (51,'Michael Madsen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52 ,'Vivien Leigh');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Clark Gable');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Olivia de Havilland');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Leslie Howard');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Hattie McDaniel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Thomas Mitchell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Barbara O\'Neil');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Butterfly McQueen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Ona Munson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Ann Rutherford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (52,'Evelyn Keyes');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53 ,'Ivana Baquero');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53,'Sergi López');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53,'Maribel Verdú');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53,'Doug Jones');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53,'Ariadna Gil');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53,'Álex Angulo');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53,'Federico Luppi');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53,'Roger Casamajor');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53,'Fernando Tielve');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (53,'Pepa Pedroche');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (54 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (55 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (56 ,'Al Pacino');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (56,'Michelle Pfeiffer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (56,'Steven Bauer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (56,'Mary Elizabeth Mastrantonio');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (56,'Robert Loggia');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (56,'F. Murray Abraham');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (56,'Miriam Colon');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (56,'Harris Yulin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (56,'Paul Shenar');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57 ,'Naomi Watts');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Adrien Brody');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Jack Black');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Thomas Kretschmann');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Jamie Bell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Lobo Chan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Kyle Chandler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Colin Hanks');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Evan Parke');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Andy Serkis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (57,'Ray Woolf');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58 ,'Charlton Heston');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Jack Hawkins');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Stephen Boyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Haya Harareet');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Hugh Griffith');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Martha Scott');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Cathy O\'Donnell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Sam Jaffe');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Frank Thring');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Terence Longdon');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'George Relph');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'André Morell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (58,'Finlay Currie');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (59 ,'Harrison Ford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (59,'Sean Connery');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (59,'Alison Doody');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (59,'Denholm Elliott');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (59,'River Phoenix');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (59,'John Rhys-Davies');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (59,'Julian Glover');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (59,'Bradley Gregg');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (59,'Andre Gregory');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (60 ,'Leonardo DiCaprio');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (60,'Matt Damon');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (60,'Jack Nicholson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (60,'Mark Wahlberg');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (60,'Alec Baldwin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (60,'Martin Sheen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (60,'Ray Winstone');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (60,'Vera Farmiga');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (60,'Anthony Anderson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (61 ,'Tom Cruise');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (91,'Brad Pitt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (91,'Christian Slater');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (91,'Antonio Banderas');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (91,'Stephen Rea');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (91,'Kirsten Dunst');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (91,'Domiziana Giordano');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (91,'Sara Stockbridge');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (91,'Thandie Newton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62 ,'Christian Bale');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Liam Neeson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Katie Holmes');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Cillian Murphy');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Michael Caine');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Morgan Freeman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Gary Oldman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Ken Watanabe');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Tom Wilkinson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Rutger Hauer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Mark Boone Junior');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Linus Roache');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Rade Serbedzija');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Richard Brake');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Christine Adams');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (62,'Jack Gleeson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (63 ,'Harrison Ford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (63,'Karen Allen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (63,'Paul Freeman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (63,'Ronald Lacey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (63,'John Rhys-Davies');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (63,'Denholm Elliott');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (63,'Wolf Kahler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (63,'Alfred Molina');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64 ,'Ewan McGregor');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Natalie Portman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Hayden Christensen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Samuel L. Jackson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Ian McDiarmid');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Ahmed Best');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Anthony Daniels');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Frank Oz');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Andrew Secombe');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Silas Carson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Kenny Baker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Christopher Lee');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Jimmy Smits');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Peter Mayhew');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Keisha Castle-Hughes');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Trisha Noble');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Bruce Spence');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (64,'Temuera Morrison');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (65 ,'Sigourney Weaver');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (65,'John Hurt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (65,'Yaphet Kotto');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (65,'Tom Skerritt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (65,'Veronica Cartwright');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (65,'Harry Dean Stanton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (65,'Ian Holm');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (66 ,'Clint Eastwood');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (66,'Lee Van Cleef');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (66,'Eli Wallach');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (66,'Aldo Giuffrè');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (66,'Mario Brega');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (66,'Luigi Scarchilli');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (66,'Rada Rassimov');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (67 ,'Mark Hamill');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (67,'Harrison Ford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (67,'Carrie Fisher');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (67,'Alec Guinness');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (67,'Billy Dee Williams');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (67,'Anthony Daniels');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (67,'David Prowse');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (67,'Kenny Baker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68 ,'Al Pacino');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Diane Keaton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Andy García');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Joe Mantegna');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Talia Shire');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Eli Wallach');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Sofia Coppola');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'George Hamilton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Raf Vallone');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Bridget Fonda');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Helmut Berger');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'John Savage');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (68,'Franco Citti');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69 ,'Mark Hamill');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Harrison Ford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Carrie Fisher');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Billy Dee Williams');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Anthony Daniels');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Peter Mayhew');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Frank Oz');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Alec Guinness');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Kenny Baker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Sebastian Shaw');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Warwick Davis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (69,'Dave Prowse');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70 ,'Jack Black');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Joan Cusack');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Mike White');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Sarah Silverman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Joey Gaydos');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Miranda Cosgrove');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Maryam Hassan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Kevin Alexander Clark');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Rebecca Brown');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Robert Tsai');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Caitlin Hale');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Aleisha Allen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Brian Falduto');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Zachary Infante');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'James Hosey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Angelo Massagli');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Cole Hawkins');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (70,'Veronica Afflerbach');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (71 ,'Charlton Heston');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (71,'Roddy McDowall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (71,'Kim Hunter');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (71,'Maurice Evans');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (71,'James Whitmore');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (71,'James Daly');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (71,'Linda Harrison');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (72 ,'Sylvester Stallone');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (72,'Richard Crenna');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (72,'Brian Dennehy');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (72,'David Caruso');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (72,'Jack Starrett');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (72,'Michael Talbott');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (72,'Chris Mulkey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73 ,'Matthew Modine');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Vincent D\'Onofrio');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'R. Lee Ermey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Adam Baldwin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Dorian Harewood');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Arliss Howard');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Kevyn Major Howard');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Ed O\'Ross');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Gary Landon Mills');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Sal López');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'John Stafford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Kieron Jecchinis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Ngc Le');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (73,'Papillon Soo Soo');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (74 ,'Roy Scheider');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (74,'Robert Shaw');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (74,'Richard Dreyfuss');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (74,'Lorraine Gary');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (74,'Murray Hamilton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (74,'Carl Gottlieb');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (74,'Jeffrey C. Kramer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Jean Reno');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Natalie Portman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Gary Oldman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Danny Aiello');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Samy Nacery');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Peter Apple');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Michael Badalucco');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Ellen Greene');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Elizabeth Regen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (75,'Maïwenn Le Besco');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Kevin Spacey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Annette Bening');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Thora Birch');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Allison Janney');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Peter Gallagher');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Mena Suvari');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Wes Bentley');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Chris Cooper');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Scott Bakula');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Sam Robards');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (76,'Barry Del Sherman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Humphrey Bogart');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Ingrid Bergman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Paul Henreid');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Claude Rains');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Conrad Veidt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Sydney Greenstreet');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Peter Lorre');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'S.Z. Sakall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Madeleine LeBeau');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Dooley Wilson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Joy Page');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'John Qualen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Leonid Kinskey');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (77,'Curt Bois');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78 ,'Audrey Tautou');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Mathieu Kassovitz');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Rufus');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Lorella Cravotta');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Serge Merlin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Jamel Debbouze');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Claire Maurier');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Clotilde Mollet');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Isabelle Nanty');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Dominique Pinon');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Artus de Penguern');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Yolande Moreau');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Urbain Cancelier');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (78,'Maurice Benichou');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (79,'Ewan McGregor');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (79,'Robert Carlyle');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (79,'Jonny Lee Miller');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (79,'Ewen Bremner');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (79,'Kelly MacDonald');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (79,'Kevin McKidd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (79,'Peter Mullan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (80,'Robert De Niro');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (80,'Cybill Shepherd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (80,'Jodie Foster');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (80,'Albert Brooks');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (80,'Harvey Keitel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (80,'Peter Boyle');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (80,'Leonard Harris');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (80,'Martin Scorsese');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (81,'Jack Nicholson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (81,'Louise Fletcher');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (81,'William Redfield');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (81,'Will Sampson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (81,'Brad Dourif');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (81,'Christopher Lloyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (81,'Danny DeVito');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (81,'Scatman Crothers');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'Uma Thurman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'David Carradine');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'Michael Madsen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'Daryl Hannah');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'Gordon Liu');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'Michael Parks');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'Bo Svenson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'Christopher Allen Nelson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'Sid Haig');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (82,'Samuel L. Jackson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'Tobey Maguire');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'Kirsten Dunst');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'Alfred Molina');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'James Franco');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'Elizabeth Banks');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'Bruce Campbell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'Rosemary Harris');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'J.K. Simmons');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'Vanessa Ferlito');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'Emily Deschanel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (83,'Stan Lee');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Hugh Jackman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Patrick Stewart');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Brian Cox');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Ian McKellen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Halle Berry');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Anna Paquin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Famke Janssen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'James Marsden');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Rebecca Romijn-Stamos');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Alan Cumming');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Aaron Stanford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Shawn Ashmore');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Kelly Hu');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Bruce Davison');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Katie Stuart');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Kea Wong');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Cotter Smith');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Bryce Hodgson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Shauna Kain');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Ty Olsson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Daniel Cudmore');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'James Kirk');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Jill Teed');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (84,'Alf Humphreys');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Shia LaBeouf');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Megan Fox');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Jon Voight');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'John Turturro');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Josh Duhamel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Tyrese Gibson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Bernie Mac');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Michael O\'Neill');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Julie White');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Rachael Taylor');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Kevin Dunn');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Amaury Nolasco');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Ronnie Sperling');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (85,'Anthony Anderson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Liam Neeson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Ewan McGregor');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Natalie Portman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Jake Lloyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Samuel L. Jackson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Ian McDiarmid');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Anthony Daniels');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Kenny Baker');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Pernilla August');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Frank Oz');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Ray Park');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Terence Stamp');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (86,'Keira Knightley');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (87 ,'Harrison Ford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (87,'Sean Young');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (87,'Daryl Hannah');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (87,'Rutger Hauer');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (87,'Edward James Olmos');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (87,'Joanna Cassidy');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (87,'Brion James');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (87,'Joe Turkel');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Martin Sheen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Marlon Brando');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Robert Duvall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Laurence Fishburne');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Frederic Forrest');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Sam Bottoms');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Albert Hall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Dennis Hopper');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Harrison Ford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'G.D Spradlin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (88,'Colleen Camp');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89 ,'Jack Nicholson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Helen Hunt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Greg Kinnear');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Cuba Gooding Jr.');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Skeet Ulrich');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Shirley Knight');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Jesse James');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Lawrence Kasdan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Yeardley Smith');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Lupe Ontiveros');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Maya Rudolph');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Tara Subkoff');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Lisa Edelstein');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Jamie Kennedy');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Harold Ramis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (89,'Julie Benz');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (90,'John Cleese');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (90,'Michael Palin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (90,'Graham Chapman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (90,'Eric Idle');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (90,'Terry Jones');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (90,'Terry Gilliam');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (90,'Sue Jones-Davies');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (90,'Carol Cleveland');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (90,'Terence Bayler');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (91 ,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (92 ,'Bill Murray');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (92,'Sigourney Weaver');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (92,'Dan Aykroyd');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (92,'Harold Ramis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (92,'Rick Moranis');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (92,'William Atherton');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (92,'Annie Potts');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (92,'Ernie Hudson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (92,'Reginald VelJohnson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (93,'Johnny Depp');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (93,'Helena Bonham Carter');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (93,'Sacha Baron Cohen');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (93,'Alan Rickman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (93,'Timothy Spall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94 ,'George Clooney');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Julia Roberts');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Matt Damon');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Andy García');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Brad Pitt');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Casey Affleck');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Scott Caan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Elliott Gould');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Bernie Mac');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Carl Reiner');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Don Cheadle');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Topher Grace');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Joshua Jackson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Holly Marie Combs');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (94,'Shane West');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (95,'Animada');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (96 ,'Arnold Schwarzenegger');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (96,'Carl Weathers');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (96,'Elpidia Carrillo');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (96,'Bill Duke');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (96,'Kevin Peter Hall');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (96,'Sonny Landham');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (96,'R.G. Armstrong');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (97,'Harrison Ford');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (97,'Kate Capshaw');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (97,'Jonathan Ke Quan');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (97,'Amrish Puri');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (97,'Philip Stone');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (97,'Roshan Seth');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (97,'David Yip');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (97,'Ric Young');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Robert De Niro');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Ray Liotta');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Joe Pesci');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Lorraine Bracco');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Samuel L. Jackson');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Paul Sorvino');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Debi Mazar');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Mike Starr');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Tony Darrow');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Frank Sivero');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Frank Vincent');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Chuck Low');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Frank DiLeo');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Clem Caserta');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Illeana Douglas');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Melissa Prophet');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Michael Imperioli');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (98,'Tobin Bell');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (99,'Nicole Kidman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (99,'Ewan McGregor');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (99,'John Leguizamo');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (99,'Jim Broadbent');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (99,'Richard Roxburgh');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (99,'David Wenham');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (99,'Jacek Koman');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (99,'Kylie Minogue');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (100 ,'Anthony Perkins');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (100,'Janet Leigh');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (100,'John Gavin');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (100,'Vera Miles');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (100,'John McIntire');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (100,'Martin Balsam');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (100,'Simon Oakland');
INSERT INTO `reparto` (`id_pelicula`,`reparto`) VALUES (100,'Patricia Hitchcock');
